<a href="https://colab.research.google.com/github/bella-xia/Deep_Learning_Using_PyTorch/blob/main/00_pytorch_fundamentals_lesson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

Wed May 24 14:30:34 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   33C    P0    45W / 400W |      0MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## 00. PyTorch Fundamentals

# Introduction to Tensors

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


Creating Tensors

In [ ]:
# scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get out of tensor
scalar.item()

7

In [ ]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
vector.ndim

1

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
# TENSOR

TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [2, 4, 5]]])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [2, 4, 5]])

In [ ]:
TENSOR[0][1]

tensor([4, 5, 6])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
# Random tensors

random_tensor = torch.rand(3, 4)

In [ ]:
random_tensor

tensor([[0.6425, 0.9163, 0.5375, 0.3816],
        [0.1590, 0.8057, 0.9789, 0.4904],
        [0.0853, 0.6749, 0.6525, 0.6479]])

In [ ]:
# Create a tensor of all zeros (helpful for masks)
zeros = torch.zeros(size=(3, 4))

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))

In [ ]:
ones.dtype

torch.float32

In [ ]:
# Create a range of tensors
one_to_ten = torch.arange(1, 11)

In [ ]:
steps = torch.arange(start=0, end=1000, step=77)

In [ ]:
steps

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
# create tensors like

In [ ]:
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeroes = torch.zeros_like(one_to_ten)

In [ ]:
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor DataType

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float_16_tensor.dtype

torch.float16

three big errors in PyTorch and Deep Learning:


*   Tensors not right datatype
*   Tensors not right shape
*   Tensors not on the right device

In [ ]:
float_16_tensor = float_32_tensor.type(torch.half)

In [ ]:
some_tensor = torch.rand(3, 4)

tensor attributes:

In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.9668, 0.9476, 0.7593, 0.0392],
        [0.5386, 0.6509, 0.6734, 0.2152],
        [0.8827, 0.3151, 0.3224, 0.2881]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


# Manipulating Tensors (tensor operations)



*   Addition
*   Subtraction
*   Multiplication (element-wise)
*   Division
*   Matrix Multiplication



In [ ]:
# addition
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiplication
tensor * 10, torch.mul(tensor, 10)

(tensor([10, 20, 30]), tensor([10, 20, 30]))

In [ ]:
# Subtraction
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])
# torch.mm
# torch.matmul

transpose

In [ ]:
tensor_B.T, tensor_B

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
torch.mm(tensor_B.T, tensor_A)

tensor([[ 76, 100],
        [103, 136]])

Finding min, max, mean, sum, etc(tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
x.dtype

torch.int64

In [ ]:
# mean -- requires a tensor of float 32 datatype
torch.mean(x, dtype=torch.float32), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
# position in tensor that has the minimum value
x.argmin()


tensor(0)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x[x.argmin().item()]

tensor(0)

In [ ]:
x[x.argmax().item()]

tensor(90)

Reshaping, stacking, squeezing and unsqueezing tensors



*   reshaping -- reshapes an input tensor to a defined shape
*   view -- Return a view of an input tensor of certain shape but keep the same memory as the original tensor
*   stacking -- combine multiple tensors
*   squeeze -- remove all `1` dimensions from a tensor
*   unsqueeze -- add a `1` dimension to a targe tensor
*   permute -- return a view of the input with dimensions permuted (swapped) in a certain way



In [ ]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# reshape -- add an extra dimension
x_reshaped = x.reshape(3, 3)
x_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
# reshape -- add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# Change view
z = x.view(1, 9)
z.shape

torch.Size([1, 9])

In [ ]:
# changing z changes x (view shares the same memory)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stack tensors on top each other
x_stacked = torch.stack([x, x, x, x])
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# squeeze

In [ ]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped.squeeze() # removes all singular dimensions

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
print(x_reshaped.unsqueeze(dim=1))
x_reshaped.shape

tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]])


torch.Size([1, 9])

In [ ]:
print(x_reshaped.unsqueeze(dim=0))
x_reshaped.shape

tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]])


torch.Size([1, 9])

In [ ]:
print(x_reshaped.unsqueeze(dim=2))
x_reshaped.shape

tensor([[[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]])


torch.Size([1, 9])

In [ ]:
# tensor permute -- rearranges the dimensions of a targe tensor
x = torch.randn(2, 3, 5)
x.size()

torch.Size([2, 3, 5])

In [ ]:
x = x.permute(2, 0,1)
x.size()

torch.Size([5, 2, 3])

In [ ]:
x_original = torch.rand(size=(224, 224, 3))
x_original.size()

torch.Size([224, 224, 3])

In [ ]:
x_permuted = x_original.permute(2, 0, 1)
x_permuted.size()

torch.Size([3, 224, 224])

In [ ]:
# permute is also return a view:

x_original[0, 0, 0] = 777777
x_permuted[0, 0, 0]

tensor(777777.)

# Indexing (selecting data from tensors)

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)

In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[:, 0, 0]

tensor([1])

In [ ]:
x[0, :, 0]

tensor([1, 4, 7])

# PyTorch Tensors & Numpy

data in numpy, want to pytorch tensor --> `torch.from_numpy(ndarray)`

In [ ]:
# Numpy array to tensor
import numpy as np

In [ ]:
array = np.arange(1., 8., 1)

In [ ]:
tensor = torch.from_numpy(array)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [ ]:
# warning: when converting from numpy --> pytorch, pytorch reflects numpy's 
# default datatype of float64 / int 64
tensor = tensor.type(torch.float32)

In [ ]:
# Change the value of array
array

array([1., 2., 3., 4., 5., 6., 7.])

In [ ]:
array = array + 1

In [ ]:
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

tensor is not a view of array!!! not gonna change

In [ ]:
tensor = tensor + 2

In [ ]:
tensor, array

(tensor([3., 4., 5., 6., 7., 8., 9.]), array([2., 3., 4., 5., 6., 7., 8.]))

In [ ]:
# Tensor to Numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Pytorch Reproducibility

In [ ]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

In [ ]:
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

In [ ]:
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

In [ ]:
print(random_tensor_C == random_tensor_D)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Running tensors and PyTorch Objects on the GPUS

Getting a GPU 

1. getting google colab
2. use your own GPU 
3. use cloud computing -- GCP, AWS, Azure --> allow to rent computers on the cloud and access them

Check for GPU access with GPU

`import torch`

`torch.cuda.is_available()`

Setup device agnostic code


`device = "cuda" if torch.cuda.is_available() else "cpu"`

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

Putting tensors (and models) on GPU

In [ ]:
import torch

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

Moving tensors back to the CPU

In [ ]:
# if tensor is on GPU, can't transform it to NumPy
tensor_back_on_cpu = tensor_on_gpu.cpu()
tensor_back_on_cpu.numpy()

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

# Exercises & Extra Curriculums